#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * Build script for @curex24/design-tokens.
 *
 * Reads tokens/tokens.json (Tokens Studio / Figma Variables shape) and emits:
 *   dist/tokens.css   – CSS variables (--curex-<kebab-path>) with a `.theme-dark`
 *                       and `[data-theme="dark"]` override block.
 *   dist/tokens.js    – CommonJS export of the resolved token tree (for RN).
 *   dist/tokens.d.ts  – TypeScript declarations for the runtime export.
 *   dist/tokens.ts    – TypeScript source mirror of tokens.js (handy for IDEs).
 *
 * Aliases of the form "{path.to.token}" are resolved to their final value.
 *
 * Usage:
 *   node scripts/build-tokens.js          # write outputs
 *   node scripts/build-tokens.js --check  # build in memory and fail if dist/ is stale
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'tokens', 'tokens.json');
const DIST = path.join(ROOT, 'dist');

const CHECK_ONLY = process.argv.includes('--check');

// ─── Helpers ──────────────────────────────────────────────────────────────

const isPlainObject = (v) =>
  v !== null && typeof v === 'object' && !Array.isArray(v);

/** A node is a "token" if it has a string `value` field. */
const isTokenNode = (v) =>
  isPlainObject(v) && typeof v.value === 'string';

/** Convert a dot-path segment into kebab-case (preserves digits). */
const toKebab = (s) =>
  String(s)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/_+/g, '-')
    .toLowerCase();

const cssVarName = (segments) =>
  '--curex-' + segments.map(toKebab).join('-');

/** Walk a token tree, calling visit(pathSegments, tokenNode) for every leaf. */
function walkTokens(node, prefix, visit) {
  if (!isPlainObject(node)) return;
  if (isTokenNode(node)) {
    visit(prefix, node);
    return;
  }
  for (const key of Object.keys(node)) {
    walkTokens(node[key], prefix.concat(key), visit);
  }
}

/** Resolve {alias.path} references against the full token document. */
function resolveValue(rawValue, root, seen = new Set()) {
  if (typeof rawValue !== 'string') return rawValue;
  // Replace every {a.b.c} occurrence — values like box-shadows can mix tokens
  // with literals, though our defaults don't currently rely on that.
  const ALIAS_RE = /\{([^}]+)\}/g;
  return rawValue.replace(ALIAS_RE, (_, refPath) => {
    if (seen.has(refPath)) {
      throw new Error(`Circular token alias detected: ${refPath}`);
    }
    const segments = refPath.split('.');
    let cur = root;
    for (const seg of segments) {
      if (!isPlainObject(cur) || !(seg in cur)) {
        throw new Error(`Unresolved token alias: {${refPath}}`);
      }
      cur = cur[seg];
    }
    if (!isTokenNode(cur)) {
      throw new Error(
        `Alias {${refPath}} does not resolve to a token (no .value)`,
      );
    }
    const next = new Set(seen);
    next.add(refPath);
    return resolveValue(cur.value, root, next);
  });
}

/** Build a flat map of cssVar -> resolvedValue for a sub-tree. */
function flattenForCss(subtree, prefix, root) {
  const out = [];
  walkTokens(subtree, prefix, (segs, node) => {
    out.push([cssVarName(segs), resolveValue(node.value, root), node.type]);
  });
  return out;
}

/** Build a nested resolved object (no `.value` wrappers) for JS consumers. */
function buildResolvedTree(subtree, root) {
  if (!isPlainObject(subtree)) return subtree;
  if (isTokenNode(subtree)) return resolveValue(subtree.value, root);
  const out = {};
  for (const key of Object.keys(subtree)) {
    out[key] = buildResolvedTree(subtree[key], root);
  }
  return out;
}

// ─── Generators ───────────────────────────────────────────────────────────

function generateCss(doc) {
  const lines = [];
  lines.push('/* AUTO-GENERATED by @curex24/design-tokens. Do not edit by hand. */');
  lines.push('/* Source: packages/design-tokens/tokens/tokens.json */');
  lines.push('');

  // Core + light semantic + components live on :root (light is the default).
  lines.push(':root {');
  for (const [name, value] of flattenForCss(doc.core || {}, ['core'], doc)) {
    lines.push(`  ${name}: ${value};`);
  }
  if (doc.semantic && doc.semantic.light) {
    for (const [name, value] of flattenForCss(
      doc.semantic.light,
      ['semantic'],
      doc,
    )) {
      lines.push(`  ${name}: ${value};`);
    }
  }
  for (const [name, value] of flattenForCss(
    doc.components || {},
    ['components'],
    doc,
  )) {
    lines.push(`  ${name}: ${value};`);
  }
  lines.push('}');
  lines.push('');

  // Dark theme overrides — apply via either `.theme-dark` class or the
  // `[data-theme="dark"]` attribute. Also mirror to the `prefers-color-scheme`
  // media query so apps without an explicit toggle still respect OS setting.
  if (doc.semantic && doc.semantic.dark) {
    const darkVars = flattenForCss(doc.semantic.dark, ['semantic'], doc);
    const block = darkVars
      .map(([name, value]) => `  ${name}: ${value};`)
      .join('\n');

    lines.push('.theme-dark,');
    lines.push('[data-theme="dark"] {');
    lines.push(block);
    lines.push('}');
    lines.push('');
    lines.push('@media (prefers-color-scheme: dark) {');
    lines.push('  :root:not([data-theme="light"]):not(.theme-light) {');
    lines.push(
      block
        .split('\n')
        .map((line) => `  ${line}`)
        .join('\n'),
    );
    lines.push('  }');
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

function stringifySorted(obj, indent = 2) {
  // Stable JSON for deterministic dist/ output.
  const sortKeys = (v) => {
    if (Array.isArray(v)) return v.map(sortKeys);
    if (isPlainObject(v)) {
      const out = {};
      for (const k of Object.keys(v).sort()) out[k] = sortKeys(v[k]);
      return out;
    }
    return v;
  };
  return JSON.stringify(sortKeys(obj), null, indent);
}

function generateJs(resolved) {
  const json = stringifySorted(resolved);
  return [
    '/* AUTO-GENERATED by @curex24/design-tokens. Do not edit by hand. */',
    '"use strict";',
    '',
    `const tokens = Object.freeze(${json});`,
    '',
    'module.exports = { tokens, default: tokens };',
    'module.exports.tokens = tokens;',
    '',
  ].join('\n');
}

function generateTs(resolved) {
  const json = stringifySorted(resolved);
  return [
    '/* AUTO-GENERATED by @curex24/design-tokens. Do not edit by hand. */',
    '/* eslint-disable */',
    `export const tokens = ${json} as const;`,
    '',
    'export type Tokens = typeof tokens;',
    'export default tokens;',
    '',
  ].join('\n');
}

function generateDts(resolved) {
  const json = stringifySorted(resolved);
  return [
    '/* AUTO-GENERATED by @curex24/design-tokens. Do not edit by hand. */',
    `export declare const tokens: ${json};`,
    'export type Tokens = typeof tokens;',
    'export default tokens;',
    '',
  ].join('\n');
}

// ─── Main ─────────────────────────────────────────────────────────────────

function build() {
  const raw = fs.readFileSync(SRC, 'utf8');
  let doc;
  try {
    doc = JSON.parse(raw);
  } catch (err) {
    throw new Error(`Failed to parse ${SRC}: ${err.message}`);
  }

  // Validate by attempting full resolution.
  walkTokens(doc, [], (_segs, node) => {
    resolveValue(node.value, doc);
  });

  // Build a single resolved tree for JS consumers. Light semantic is exposed
  // at `tokens.semantic` for backward-compat with apps that don't need the
  // dark variant directly; both light and dark also live under
  // `tokens.themes.{light,dark}` for theme-aware code.
  const resolvedCore = buildResolvedTree(doc.core || {}, doc);
  const resolvedComponents = buildResolvedTree(doc.components || {}, doc);
  const resolvedLight = buildResolvedTree(
    (doc.semantic && doc.semantic.light) || {},
    doc,
  );
  const resolvedDark = buildResolvedTree(
    (doc.semantic && doc.semantic.dark) || {},
    doc,
  );

  const resolved = {
    core: resolvedCore,
    components: resolvedComponents,
    semantic: resolvedLight,
    themes: {
      light: resolvedLight,
      dark: resolvedDark,
    },
  };

  const outputs = {
    'tokens.css':   generateCss(doc),
    'tokens.js':    generateJs(resolved),
    'tokens.ts':    generateTs(resolved),
    'tokens.d.ts':  generateDts(resolved),
  };

  if (CHECK_ONLY) {
    let stale = false;
    for (const [name, content] of Object.entries(outputs)) {
      const target = path.join(DIST, name);
      let existing = '';
      try {
        existing = fs.readFileSync(target, 'utf8');
      } catch (_) {
        existing = '';
      }
      if (existing !== content) {
        console.error(`[design-tokens] dist/${name} is out of date.`);
        stale = true;
      }
    }
    if (stale) {
      console.error(
        '[design-tokens] Run `pnpm --filter @curex24/design-tokens build` to regenerate.',
      );
      process.exit(1);
    }
    console.log('[design-tokens] dist/ is up to date.');
    return;
  }

  fs.mkdirSync(DIST, { recursive: true });
  for (const [name, content] of Object.entries(outputs)) {
    fs.writeFileSync(path.join(DIST, name), content);
    console.log(`[design-tokens] wrote dist/${name}`);
  }
}

try {
  build();
} catch (err) {
  console.error(`[design-tokens] build failed: ${err.message}`);
  process.exit(1);
}
