/**
 * Structured types for the advanced "skill runner" — what turns each
 * marketing skill from a static card into a real executable workflow.
 *
 * These types are intentionally additive: they live alongside the existing
 * `MarketingSkill` type in `lib/data.ts` and are referenced by the optional
 * `advanced` field on every skill, so legacy code paths keep working.
 */

// ─── Inputs ──────────────────────────────────────────────────────────────────

export type SkillInputType =
  | 'text'
  | 'textarea'
  | 'url'
  | 'number'
  | 'select'
  | 'multiselect'
  | 'boolean';

export interface SkillInput {
  /** Variable name referenced inside `promptTemplate` as `{{name}}`. */
  name: string;
  label: string;
  type: SkillInputType;
  required?: boolean;
  placeholder?: string;
  helper?: string;
  /** For select / multiselect. */
  options?: string[];
  /** Default value if the user submits without changing the field. */
  defaultValue?: string | string[] | number | boolean;
  /** Optional max length for free-text inputs. */
  maxLength?: number;
}

// ─── Outputs ─────────────────────────────────────────────────────────────────

export type SkillOutputKind =
  | 'markdown' // long-form brief
  | 'copy' // ready-to-ship copy block
  | 'json' // structured spec (CSV/JSON-LD/dataLayer/etc.)
  | 'table' // rows for the artifact "Table" tab
  | 'image' // visual generated by /api/ai/image
  | 'code'; // emitted code (React component, JSON-LD, GTM JSON, etc.)

export interface SkillOutput {
  /** Stable key referenced by the runner UI. */
  key: string;
  label: string;
  kind: SkillOutputKind;
  /** Short description shown above the artifact. */
  description?: string;
  /** Optional file extension hint for the download button. */
  downloadExtension?: string;
}

// ─── Tools the skill can call ────────────────────────────────────────────────

export type SkillTool =
  | 'kpis.northStar'
  | 'kpis.acquisition'
  | 'kpis.activation'
  | 'kpis.retention'
  | 'profile'
  | 'campaigns'
  | 'experiments'
  | 'contentCalendar'
  | 'seoPages'
  | 'keywordClusters'
  | 'lifecycleFlows'
  | 'planItems'
  | 'image'
  | 'webFetch';

// ─── Success criteria / evals ────────────────────────────────────────────────

export interface SkillRubricCriterion {
  /** Short id, e.g. "brand_voice", "specificity", "cta_strength". */
  id: string;
  /** Human-readable rubric line shown to the critic LLM. */
  description: string;
  /** Weight 1-5 used by the critic to compute the overall score. */
  weight: 1 | 2 | 3 | 4 | 5;
}

// ─── The advanced skill config ───────────────────────────────────────────────

export type SkillTier = 'free' | 'pro';

export interface AdvancedSkillConfig {
  /**
   * Skill-specific persona + guardrails. Appended to the global brand system
   * prompt by the chat route.
   */
  systemPrompt: string;
  /**
   * Handlebars-lite template. Variables `{{name}}` are substituted from the
   * user's form submission; arrays are joined with commas. Unknown vars fall
   * back to "—".
   */
  promptTemplate: string;
  inputs: SkillInput[];
  outputs: SkillOutput[];
  tools?: SkillTool[];
  /** Brand / compliance guardrails applied to every run. */
  guardrails?: string[];
  /** Critic rubric used by `/api/ai/critique`. */
  successCriteria?: SkillRubricCriterion[];
  /** Model recommendation surfaced in the UI. */
  model?: 'gpt-4o-mini' | 'gpt-4o' | 'dall-e-3';
  tier?: SkillTier;
  /**
   * If set, after the main run we generate a visual at this aspect ratio.
   * width/height in pixels — the server picks the closest supported size.
   */
  visual?: { width: number; height: number; promptHint: string };
}

// ─── Skill run + critique results (client side) ──────────────────────────────

export type SkillInputValue = string | string[] | number | boolean;

export interface SkillRunRequest {
  skillId: string;
  inputs: Record<string, SkillInputValue>;
  /** Pre-formatted org context block (KPIs, profile, etc.). */
  orgContext?: string;
}

export interface SkillCritique {
  overallScore: number; // 0-100
  scores: Array<{ id: string; score: number; comment: string }>;
  weakestSection: string;
  suggestion: string;
}
